server:
  port: 9002
spring:
  application:
    name: cancal
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
canal:
  client:
    instances:
      example:
        host: 192.168.235.21
        port: 11111